WINDOW_WIDTH, WINDOW_HEIGHT = love.window.getDesktopDimensions()

VIRTUAL_WIDTH = 1280	
VIRTUAL_HEIGHT = 720

PLATE_WIDTH = 100
PLATE_HEIGHT = 20
WEINER_GIRTH = 100
--Top floor Y is stephen.height + 30
TOP_FLOORY = 160
FLOOR_HEIGHT = 100
GROUND_FLOOR_STEPHENY = VIRTUAL_HEIGHT - FLOOR_HEIGHT - 130
LADDER_WIDTH = 110
LADDERX = 220